language: php

php:
  - 5.3

env:
  - DB=mysql

matrix:
  include:
    - php: 5.3
      env:
        - PHPCS=1

before_script:
  - sh -c "mysql -e 'CREATE DATABASE qdnatool_test;'"
  - chmod -R 777 ./app/tmp
  - composer install --dev --no-interaction --prefer-source
  - sh -c "if [ '$PHPCS' = '1' ]; then pear channel-discover pear.cakephp.org; fi"
  - sh -c "if [ '$PHPCS' = '1' ]; then pear install --alldeps cakephp/CakePHP_CodeSniffer; fi"
  - phpenv rehash
  - echo -e "<?php\nclass DATABASE_CONFIG {\n\n\tpublic \$test = array(\n\t\t'datasource' => 'Database/Mysql',\n\t\t'database' => 'qdnatool_test',\n\t\t'host' => '0.0.0.0',\n\t\t'login' => 'travis',\n\t\t'persistent' => false,\n\t);\n}" > app/Config/database.php
 
script:
  - sh -c "if [ '$PHPCS' = '1' ]; then phpcs -p --extensions=php --standard=CakePHP --ignore=Plugin --ignore=Vendor --ignore=webroot/js/ckeditor -n ./app; else cd ./app; ../vendors/bin/cake test app AllTests --stderr; fi"

notifications:
  email: false
